export { default as ClassesTab } from './Classes'
export { default as EmployeesTab } from './Employees'
export { default as PaymentsTab } from './Payments'
export { default as CourseTab } from './Tabs'
export { default as CourseDetails } from './Details'
