version: '3'

services:
  frontend:
    restart: unless-stopped
    image: cchcprod.azurecr.io/frontend-cchc-prod:latest
    ports:
      - '80:80'
    env_file:
      - .env
    container_name: cchc-frontend
    domainname: fcchc-frontend
    stdin_open: true
   
