version: '3'
services:
  frontend:
    build:
      context: .
    ports:
      - '3020:3000'
    env_file:
      - .env
    container_name: cchc-frontend
    stdin_open: true
    volumes:
      - .:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
