version: '3'

services:
  frontend-test:
    restart: unless-stopped
    build:
      context: .
    ports:
      - '5190:80'
    env_file:
      - .env
    container_name: fcchc-frontend-test
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
