version: '3'

services:
  frontend:
    restart: unless-stopped
    build:
      context: .
    ports:
      - '5200:80'
    env_file:
      - .env
    container_name: cchc-frontend
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
