export default {
  GET_CALENDAR_EVENTS: 'GET_CALENDAR_EVENTS',
  GET_EVENTS_LIST: 'GET_EVENTS_LIST',
  SET_EVENTS_TOTALS: 'SET_EVENTS_TOTALS',
  GET_VISIT_DETAILS: 'GET_VISIT_DETAILS',
  ASSISTANCE_TYPE_TOGGLE: 'ASSISTANCE_TYPE_TOGGLE',
  GET_ASSISTANCE_CONSTRUCTION: 'GET_ASSISTANCE_CONSTRUCTION',
  GET_ATTENDED_EMPLOYEES: 'GET_ATTENDED_EMPLOYEES',
  GET_PERSONAL_INTERVENTION_DETAILS: 'GET_PERSONAL_INTERVENTION_DETAILS',
  GET_ATTENTION_LIST: 'GET_ATTENTION_LIST',
  SET_ATTENTION_TOTALS: 'SET_ATTENTION_TOTALS',
  GET_EMPLOYEES_TO_ATTEND: 'GET_EMPLOYEES_TO_ATTEND',
  GET_CALENDAR_STATS: 'GET_CALENDAR_STATS',
  GET_ITEMS: 'GET_ITEMS',
  TOTAL_USERS: 'TOTAL_USERS',
  EMPLOYEE_ATTENDED_HISTORICLY: 'EMPLOYEE_ATTENDED_HISTORICLY',
  GET_VISIT_STATISTICS: 'GET_VISIT_STATISTICS',
  GET_STATISTICS_PRINT: 'GET_STATISTICS_PRINT'
}
