export default {
  GET_CALENDAR_EVENTS: 'GET_CALENDAR_EVENTS',
  GET_EVENTS_LIST: 'GET_EVENTS_LIST',
  SET_EVENTS_TOTALS: 'SET_EVENTS_TOTALS',
  GET_VISIT_DETAILS: 'GET_VISIT_DETAILS',
  ASSISTANCE_TYPE_TOGGLE: 'ASSISTANCE_TYPE_TOGGLE',
  GET_ASSISTANCE_CONSTRUCTION: 'GET_ASSISTANCE_CONSTRUCTION',
  GET_ATTENDED_EMPLOYEES: 'GET_ATTENDED_EMPLOYEES',
  GET_PERSONAL_INTERVENTION_DETAILS: 'GET_PERSONAL_INTERVENTION_DETAILS'
}
