export default {
  BENEFIT_UPDATE_CREATE: 'BENEFIT_UPDATE_CREATE',
  BENEFIT_TOGGLE_CREATE: 'BENEFIT_TOGGLE_CREATE',
  GET_BENEFITS: 'GET_BENEFITS',
  SET_TOTAL_BENEFITS: 'SET_TOTAL_BENEFITS',
  GET_BENEFIT_DETAILS: 'GET_BENEFIT_DETAILS'
}
