export default {
  GET_CONSTRUCTION_TYPOLOGIES: 'GET_CONSTRUCTION_TYPOLOGIES',
  GET_CHARGES: 'GET_CHARGES',
  GET_REGIONS: 'GET_REGIONS',
  GET_MARITAL_STATUS: 'GET_MARITAL_STATUS',
  GET_SCHOLARSHIP: 'GET_SCHOLARSHIP',
  GET_NATIONALITIES: 'GET_NATIONALITIES',
  GET_BANKS: 'GET_BANKS',
  GET_RSH: 'GET_RSH',
  GET_RELATIONSHIPS: 'GET_RELATIONSHIPS',
  GET_ACTIVITIES: 'GET_ACTIVITIES'
}
