export default {
  BUSINESS_TOGGLE_CREATE: 'BUSINESS_TOGGLE_CREATE',
  BUSINESS_UPDATE_FILTERS: 'BUSINESS_UPDATE_FILTERS',
  BUSINESS_UPDATE_CREATE: 'BUSINESS_UPDATE_CREATE',
  BUSINESS_GET_DIVISIONS: 'BUSINESS_GET_DIVISIONS',
  BUSINESS_GET_CONTACTS: 'BUSINESS_GET_CONTACTS',
  BUSINESS_GET_CONSTRUCTIONS: 'BUSINESS_GET_CONSTRUCTIONS',
  GET_BUSINESSES: 'GET_BUSINESSES',
  SET_BUSINESSES_TOTAL: 'SET_BUSINESSES_TOTAL',
  GET_BUSINESS_DETAIL: 'GET_BUSINESS_DETAIL',
  GET_COMPANY: 'GET_COMPANY'
}
