export default {
  BUSINESS_TOGGLE_CREATE: 'BUSINESS_TOGGLE_CREATE',
  BUSINESS_UPDATE_FILTERS: 'BUSINESS_UPDATE_FILTERS',
  BUSINESS_UPDATE_CREATE: 'BUSINESS_UPDATE_CREATE',
  BUSINESS_GET_DIVISIONS: 'BUSINESS_GET_DIVISIONS',
  BUSINESS_GET_CONTACTS: 'BUSINESS_GET_CONTACTS',
  BUSINESS_GET_CONSTRUCTIONS: 'BUSINESS_GET_CONSTRUCTIONS',
  GET_BUSINESSES: 'GET_BUSINESSES',
  GET_BUSINESS_DETAIL: 'GET_BUSINESS_DETAIL'
}
