export default {
  GET_CONSTRUCTIONS: 'GET_CONSTRUCTIONS',
  GET_CONSTRUCTION_DETAILS: 'GET_CONSTRUCTION_DETAILS',
  GET_CONSTRUCTIONS_TYPOLOGIES: 'GET_CONSTRUCTIONS_TYPOLOGIES',
  GET_CONSTRUCTIONS_ECONOMIC_SECTOR: 'GET_CONSTRUCTIONS_ECONOMIC_SECTOR',
  GET_CONSTRUCTIONS_CONTACTS: 'GET_CONSTRUCTIONS_CONTACTS',
  CONSTRUCTIONS_UPDATE_FILTERS: 'CONSTRUCTIONS_UPDATE_FILTERS'
}
