export default {
  GET_COURSES: 'GET_COURSES',
  SET_TOTAL_COURSES: 'SET_TOTAL_COURSES',
  GET_COURSE_DETAILS: 'GET_COURSE_DETAILS',
  SET_TOTAL_COURSES_DOCS: 'SET_TOTAL_COURSES_DOCS',
  GET_COURSES_DOCS: 'GET_COURSES_DOCS',
  GET_COURSE_DOC_DETAILS: 'GET_COURSE_DOC_DETAILS',
  GET_EXTRA_PAYMENTS: 'GET_EXTRA_PAYMENTS',
  SET_TOTAL_EXTRA_PAYMENTS: 'SET_TOTAL_EXTRA_PAYMENTS'
}
