export default {
  GET_COURSES: 'GET_COURSES',
  SET_TOTAL_COURSES: 'SET_TOTAL_COURSES',
  GET_COURSE_DETAILS: 'GET_COURSE_DETAILS',
  SET_TOTAL_COURSES_DOCS: 'SET_TOTAL_COURSES_DOCS',
  GET_COURSES_DOCS: 'GET_COURSES_DOCS',
  GET_COURSE_DOC_DETAILS: 'GET_COURSE_DOC_DETAILS',
  GET_EXTRA_PAYMENTS: 'GET_EXTRA_PAYMENTS',
  SET_TOTAL_EXTRA_PAYMENTS: 'SET_TOTAL_EXTRA_PAYMENTS',
  GET_STUDENTS_COURSE: 'GET_STUDENTS_COURSE',
  GET_SCORES: 'GET_SCORES',
  SET_TOTAL_SCORES: 'SET_TOTAL_SCORES',
  GET_STATUS: 'GET_STATUS',
  SET_TOTAL_STATUS: 'SET_TOTAL_STATUS'
}
