export default {
  HOME_TYPE_TOGGLE: 'HOME_TYPE_TOGGLE',
  GET_VISITS_HOME: 'GET_VISITS_HOME',
  GET_HOME_BENEFITS_DELIVERED: 'GET_HOME_BENEFITS_DELIVERED',
  GET_HOME_LAST_ATTENTIONS: 'GET_HOME_LAST_ATTENTIONS'
}
