export default {
  GET_AGREEMENTS: 'GET_AGREEMENTS',
  SET_TOTAL_AGREEMENTS: 'SET_TOTAL_AGREEMENTS',
  GET_AGREEMENT_DETAILS: 'GET_AGREEMENT_DETAILS',
  GET_AGREEMENT_EMPLOYEES: 'GET_AGREEMENT_EMPLOYEES',
  SET_TOTAL_AGREEMENT_EMPLOYEES: 'SET_TOTAL_AGREEMENT_EMPLOYEES',
  GET_HOUSING_EMPLOYEE_DETAILS: 'GET_HOUSING_EMPLOYEE_DETAILS',
  UPDATE_EMPLOYEE_SAVING: 'UPDATE_EMPLOYEE_SAVING'
}
