export default {
  GET_INCLUSION_CASES: 'GET_INCLUSION_CASES',
  GET_INCLUSIONCASE_DETAILS: 'GET_INCLUSIONCASE_DETAILS',
  GET_CHARGE_METHODS: 'GET_CHARGE_METHODS',
  GET_DASHBOARD_STATS: 'GET_STATS',
  GET_CASE_APPROBATION_DETAILS: 'GET_CASE_APPROBATION_DETAILS',
  GET_CASE_REJECTION_DETAILS: 'GET_CASE_REJECTION_DETAILS',
  GET_CASE_CLOSE_DETAILS: 'GET_CASE_CLOSE_DETAILS'
}
