export default {
  GET_POLLS: 'GET_POLLS',
  GET_QUESTION_TYPES: 'GET_QUESTION_TYPES',
  GET_POLL_DETAILS: 'GET_POLL_DETAILS',
  SET_TOTAL_POLLS: 'SET_TOTAL_POLLS',
  GET_QUESTIONS: 'GET_QUESTIONS',
  SET_TOTAL_QUESTIONS: 'SET_TOTAL_QUESTIONS',
  GET_MODULE_POLLS: 'GET_MODULE_POLLS'
}
