export default {
  GET_POLLS: 'GET_POLLS',
  GET_QUESTION_TYPES: 'GET_QUESTION_TYPES',
  GET_POLL_DETAILS: 'GET_POLL_DETAILS',
  SET_TOTAL_POLLS: 'SET_TOTAL_POLLS',
  GET_QUESTIONS: 'GET_QUESTIONS',
  SET_TOTAL_QUESTIONS: 'SET_TOTAL_QUESTIONS',
  GET_QUESTION_DETAILS: 'GET_QUESTION_DETAILS',
  GET_MODULE_POLLS: 'GET_MODULE_POLLS',
  GET_POLL_ANSWERS: 'GET_POLL_ANSWERS',
  POLL_AVAILABLE_TOGGLE: 'POLL_AVAILABLE_TOGGLE',
  UPDATE_MODULE_POLL: 'UPDATE_MODULE_POLL'
}
