export default {
  GET_PROTOCOLS: 'GET_PROTOCOLS',
  GET_MODULE_PROTOCOLS: 'GET_MODULE_PROTOCOLS',
  PROTOCOLS_TOGGLE_CREATE: 'PROTOCOLS_TOGGLE_CREATE',
  CREATE_PROTOCOL: 'CREATE_PROTOCOL',
  UPDATE_PROTOCOL: 'UPDATE_PROTOCOL',
  DELETE_PROTOCOL: 'DELETE_PROTOCOL',
  GET_PROTOCOL_DETAILS: 'GET_PROTOCOL_DETAILS'
}
