export default {
  QUESTIONS_TOGGLE_CREATE: 'QUESTIONS_TOGGLE_CREATE',
  GET_QUESTION_DETAILS: 'GET_QUESTION_DETAILS',
  GET_QUESTIONS: 'GET_QUESTIONS',
  SET_TOTAL_QUESTIONS: 'SET_TOTAL_QUESTIONS'
}
