export default {
  SET_EMPLOYEE_ID: 'SET_EMPLOYEE_ID',
  QE_GET_EMPLOYEE_DETAILS: 'QE_GET_EMPLOYEE_DETAILS',
  QE_GET_QUESTIONS: 'QE_GET_QUESTIONS',
  QE_SET_TOTAL_QUESTIONS: 'QE_SET_TOTAL_QUESTIONS',
  QE_ADD_QUESTION: 'QE_ADD_QUESTION'
}
