export default {
  QUESTIONS_TOGGLE_CREATE: 'QUESTIONS_TOGGLE_CREATE',
  GET_QUESTION_DETAILS: 'GET_QUESTION_DETAILS',
  GET_QUESTIONS: 'GET_QUESTIONS',
  SET_TOTAL_QUESTIONS: 'SET_TOTAL_QUESTIONS',
  GET_DISTRIBUTION_STATS: 'GET_DISTRIBUTION_STATS',
  GET_LAST_QUESTIONS: 'GET_LAST_QUESTIONS',
  GET_GENERAL_STATS: 'GET_GENERAL_STATS',
  UPDATE_QUERY: 'UPDATE_QUERY',
  UPDATE_UI_FILTERS: 'UPDATE_UI_FILTERS',
  UPDATE_SELECTED_LIST: 'UPDATE_SELECTED_LIST',
  GET_ASSIGNATION_STATS: 'GET_ASSIGNATION_STATS',
  GET_MAX_HOURS: 'GET_MAX_HOURS'
}
