export default {
  GET_SCHEDULE_LIST: 'GET_SCHEDULE_LIST',
  GET_SCHEDULE_DETAILS: 'GET_SCHEDULE_DETAILS',
  GET_SCHEDULE_MEETINGS: 'GET_SCHEDULE_MEETINGS',
  CREATE_SCHEDULE_MEETING: 'CREATE_SCHEDULE_MEETING',
  UPDATE_SCHEDULE_MEETING: 'UPDATE_SCHEDULE_MEETING',
  CREATE_SCHEDULE_APPROBATION: 'CREATE_SCHEDULE_APPROBATION',
  CREATE_UPDATE_SCHEDULE_SEND_STATUS: 'CREATE_UPDATE_SCHEDULE_SEND_STATUS',
  UPDATE_SCHEDULE_BENEFIT_MONTHS: 'UPDATE_SCHEDULE_BENEFIT_MONTHS',
  GET_SCHEDULE_BENEFITS: 'GET_SCHEDULE_BENEFITS'
}
