export default {
  GET_SCHEDULE_LIST: 'GET_SCHEDULE_LIST',
  GET_SCHEDULE_DETAILS: 'GET_SCHEDULE_DETAILS',
  GET_SCHEDULE_MEETINGS: 'GET_SCHEDULE_MEETINGS',
  CREATE_SCHEDULE_MEETING: 'CREATE_SCHEDULE_MEETING',
  UPDATE_SCHEDULE_MEETING: 'UPDATE_SCHEDULE_MEETING'
}
