export default {
  APPLICATION_TOGGLE_CREATE: 'APPLICATION_TOGGLE_CREATE',
  GET_APPLICATIONS: 'GET_APPLICATIONS',
  SET_TOTAL_APPLICATIONS: 'SET_TOTAL_APPLICATIONS',
  GET_APPLICATION_DETAILS: 'GET_APPLICATION_DETAILS',
  GET_SCHOLARSHIPS_TYPES: 'GET_SCHOLARSHIPS_TYPES',
  POSTULATION_UPDATE_CREATE: 'POSTULATION_UPDATE_CREATE'
}
