export default {
  APPLICATION_TOGGLE_CREATE: 'APPLICATION_TOGGLE_CREATE',
  GET_APPLICATIONS: 'GET_APPLICATIONS',
  SET_TOTAL_APPLICATIONS: 'SET_TOTAL_APPLICATIONS',
  GET_APPLICATION_DETAILS: 'GET_APPLICATION_DETAILS',
  GET_SCHOLARSHIPS_TYPES: 'GET_SCHOLARSHIPS_TYPES',
  POSTULATION_UPDATE_CREATE: 'POSTULATION_UPDATE_CREATE',
  GET_CAREERS: 'GET_CAREERS',
  GET_APPROVED_SCHOLARSHIPS: 'GET_APPROVED_SCHOLARSHIPS',
  SET_APPROVED_SCHOLARSHIPS_TOTAL: 'SET_APPROVED_SCHOLARSHIPS_TOTAL',
  GET_APPROVED_SCHOLARSHIP: 'GET_APPROVED_SCHOLARSHIP'
}
