export default {
  GET_CASES: 'GET_CASES',
  SET_TOTAL_CASES: 'SET_TOTAL_CASES',
  GET_CASES_DETAILS: 'GET_CASES_DETAILS',
  SET_FILTERS: 'SET_FILTERS',
  SET_TAGS: 'SET_TAGS',
  GET_CASES_FOR_SELECTED: 'GET_CASES_FOR_SELECTED',
  GET_INTERVENTION_PLANS: 'GET_INTERVENTION_PLANS',
  SET_INTERVENTION_PLAN_TOTAL: 'SET_INTERVENTION_PLAN_TOTAL',
  GET_CASE_BY_ID: 'GET_CASE_BY_ID',
  GET_DERIVATION_DETAILS: 'GET_DERIVATION_DETAILS'
}
