export default {
  GET_CASES: 'GET_CASES',
  SET_TOTAL_CASES: 'SET_TOTAL_CASES',
  GET_CASES_DETAILS: 'GET_CASES_DETAILS',
  SET_FILTERS: 'SET_FILTERS',
  SET_TAGS: 'SET_TAGS',
  GET_CASES_FOR_SELECTED: 'GET_CASES_FOR_SELECTED',
  GET_INTERVENTION_PLANS: 'GET_INTERVENTION_PLANS',
  GET_INTERVENTION_PLANS_CALENDAR: 'GET_INTERVENTION_PLANS_CALENDAR',
  SET_INTERVENTION_PLAN_TOTAL: 'SET_INTERVENTION_PLAN_TOTAL',
  CREATE_TASK_INTERVENTION_PLAN: 'CREATE_TASK_INTERVENTION_PLAN',
  UPDATE_TASK_INTERVENTION_PLAN: 'UPDATE_TASK_INTERVENTION_PLAN',
  DELETE_TASK_INTERVENTION_PLAN: 'DELETE_TASK_INTERVENTION_PLAN',
  GET_CASE_BY_ID: 'GET_CASE_BY_ID',
  GET_DERIVATION_DETAILS: 'GET_DERIVATION_DETAILS',
  GET_PLAN_TASK_DETAILS: 'GET_PLAN_TASK_DETAILS'
}
