export default {
  GET_UNEMPLOYED_LIST: 'GET_UNEMPLOYED_LIST',
  GET_BENEFITS_HISTORY: 'GET_BENEFITS_HISTORY',
  GET_TOTAL_UNEMPLOYED: 'GET_TOTAL_UNEMPLOYED',
  GET_TOTAL_BENEFITS_HISTORY: 'GET_TOTAL_BENEFITS_HISTORY',
  GET_UNEMPLOYED: 'GET_UNEMPLOYED',
  SET_QUERY_UNEMPLOYED: 'SET_QUERY_UNEMPLOYED',
  SET_FILTERS: 'SET_FILTERS',
  SET_QUERY: 'SET_QUERY'
}
